from snakemake.utils import min_version

min_version("6.4.1")


# load rules
include: "rules/opsins.smk"

transcriptomes, = glob_wildcards("resources/{transcriptome}.pep")


# target rule
rule all:
    input:
        expand("results/opsins/{transcriptome}.opsins.fasta", transcriptome=transcriptomes)
